### ISSUE TITLE
[FE] Menambahkan Makanan Dikonsumsi

### ISSUE THREAD

**Issue by monicaoktviona** [KaloriKu/KaloriKu_Frontend#4]
# User Story
Sebagai Registered User dari website KaloriKu, saya ingin dapat menambahkan makanan (satu atau lebih) secara sekaligus ke dalam daftar makanan dikonsumsi.

# Task
- [x] Mengimplementasikan antarmuka pengguna yang memungkinkan pengguna untuk memilih makanan-makanan yang tersedia di sistem untuk ditambahkan ke daftar makanan dikonsumsi
- [x] Mengimplementasikan tombol "tambah makanan saya" yang akan mengarahkan pengguna ke halaman "Makanan Saya"
- [x] Mengimplementasikan notifikasi sukses jika makanan berhasil disimpan ke daftar makanan dikonsumsi
- [x] Mengimplementasikan notifikasi gagal jika makanan tidak berhasil disimpan ke daftar makanan dikonsumsi
