### ISSUE TITLE
[FE] Melihat Daftar Makanan

### ISSUE THREAD

**Issue by airelcamilo** [KaloriKu/KaloriKu_Frontend#5]
# User Story
Sebagai Registered User dari website KaloriKu, saya ingin dapat melihat daftar makanan yang tersimpan dalam sistem untuk dapat memilih makanan yang saya konsumsi. Detail yang ditampilkan terdiri dari kalori, lemak, protein, dan karbohidrat dalam makanan tersebut.

# Task
- [ ] Mengimplementasikan tombol "Melihat Daftar Makanan" yang akan mengarahkan pengguna ke halaman "Daftar Makanan".
- [ ] Mengimplementasikan antarmuka pengguna yang menampilkan daftar makanan. Daftar makanan berisi nama, kalori, lemak, protein, dan karbohidrat makanan tersebut.
- [ ] Mengimplementasikan antarmuka pengguna yang menampilkan notifikasi apabila daftar makanan gagal ditampilkan.
