### ISSUE TITLE
[FE] Melihat Daftar Makanan Dikonsumsi

### ISSUE THREAD

**Issue by monicaoktviona** [KaloriKu/KaloriKu_Frontend#8]
# User Story
Sebagai Registered User dari website KaloriKu, saya ingin dapat melihat daftar makanan dikonsumsi yang tersimpan dalam sistem per harinya. Detail yang ditampilkan terdiri dari timestamp, makanan yang dikonsumsi, total kalori, lemak, protein, dan karbohidrat per harinya.

# Task
- [x] Menampilkan daftar makanan dikonsumsi milik user yang diurutkan berdasarkan timestamp paling baru
- [x] Menampilkan detail per harinya meliputi timestamp, makanan yang dikonsumsi, total kalori, lemak, protein, dan karbohidrat
- [x] Menampilkan pesan gagal jika sistem gagal mengambil daftar makanan dikonsumsi dari database
