### ISSUE TITLE
[FE] Melihat Artikel

### ISSUE THREAD

**Issue by debbytrinita** [KaloriKu/KaloriKu_Frontend#9]
# User story
Sebagai Registered user dari website KaloriKu, saya ingin dapat melihat artikel terkait dengan hal-hal yang dapat mendukung pola hidup sehat serta pola makan yang sehat

# Task
- [ ] Mengimplementasikan menu "Artikel" yang akan mengarahkan pengguna ke halaman "Artikel".
- [ ] Mengimplementasikan antarmuka pengguna yang menampilkan daftar judul yang tersimpan pada sistem 
- [ ] Mengimplementasikan antarmuka pengguna yang menampilkan keseluruhan isi artikel
